apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workflows.oceanprotocol.com
spec:
  group: oceanprotocol.com
  versions:
    - name: v1alpha
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: workflows
    singular: workflow
    kind: WorkFlow
    shortNames:
    - wf
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        spec:
          description: 'Workflow specification for a cumputing workflow based on Ocean Protocol.
            More info: https://github.com/oceanprotocol/OEPs/tree/master/12'
          properties:
            stages:
              type: array
              items:
                type: object
                description: The description for the items
                properties:
                    index:
                      type: integer
                      description: The description for the index
                    input:
                      type: array
                      description: The description for the input
                      items:
                        type: object
                        description: The description for the items
                        properties:
                          index:
                            type: integer
                            description: The description for the index
                          id:
                            type: string
                            description: The description for the id
                          url:
                              type: string
                              description: The description for the url                          
                    algorithm:
                      type: array
                      description: The description for the algorithm
                      items:
                        type: object
                        description: The description for the items
                        properties:
                          id:
                            type: string
                            description: The description for the id
                          url:
                                type: string
                                description: The description for the url
                          container:
                                  type: object
                                  description: The description for the container
                                  properties:
                                    image:
                                      type: string
                                      description: The description for the image
                                    tag:
                                      type: string
                                      description: The description for the tag
                                      entrypoint:
                                      type: string
                                      description: The description for the entrypoint
                    output:
                      type: array
                      description: The description for the output
                      items:
                        type: object
                        description: The description for the items
                        properties:
                          nodeUri:
                            type: string
                            description: The description for the id
                          brizoUrl:
                            type: string
                            description: The description for the id
                          brizoAddress:
                            type: string
                            description: The description for the id
                          metadataUrl:
                            type: string
                            description: The description for the id
                          secretStoreUrl:
                            type: string
                            description: The description for the id
                          metadata:
                            type: object
                            description: The description for the id
                          whitelist:
                            type: object
                            description: The description for the id
                          publishoutput:
                            type: boolean
                            description: The description for the id
                          publishalgolog:
                            type: boolean
                            description: The description for the id
                    compute:
                      type: array
                      description: The description for the compute
                      items:
                        type: object
                        description: The description for the items
                        properties:
                          Instances:
                            type: integer
                            description: The description for the Instances
                          namespace:
                            type: string
                            description: The description for the Instances
                          maxtime:
                            type: integer
                            description: The description for the Instances
                          resources:
                              type: object
                              description: The description for the Instances
